# SN-Corporate-Rating-Model-V2

{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6e19262f-3151-48e5-8be3-e3a98fb4b9e4",
   "metadata": {},
   "outputs": [],
   "source": [
    "import logging\n",
    "\n",
    "from sn_rating_v2 import QuantInputs, QualInputs, RatingModel\n",
    "\n",
    "\n",
    "def main() -> None:\n",
    "    logging.basicConfig(level=logging.INFO)\n",
    "\n",
    "    # --- Financial ratios (t0, t1, t2) ---\n",
    "\n",
    "    fin_t0 = {\n",
    "        \"debt_ebitda\": 3.2,\n",
    "        \"net_debt_ebitda\": 2.8,\n",
    "        \"debt_equity\": 1.5,\n",
    "        \"debt_capital\": 0.55,\n",
    "        \"ffo_debt\": 0.18,\n",
    "        \"fcf_debt\": 0.12,\n",
    "        \"interest_coverage\": 0.8,\n",
    "        \"fixed_charge_coverage\": 1.4,\n",
    "        \"dscr\": 0.95,\n",
    "        \"ebitda_margin\": 0.18,\n",
    "        \"ebit_margin\": 0.12,\n",
    "        \"roa\": 0.055,\n",
    "        \"roe\": 0.11,\n",
    "        \"capex_dep\": 1.3,\n",
    "        \"current_ratio\": 1.3,\n",
    "        \"rollover_coverage\": 1.1,\n",
    "    }\n",
    "\n",
    "    fin_t1 = {\n",
    "        \"debt_ebitda\": 3.6,\n",
    "        \"net_debt_ebitda\": 3.1,\n",
    "        \"debt_equity\": 1.6,\n",
    "        \"debt_capital\": 0.57,\n",
    "        \"ffo_debt\": 0.17,\n",
    "        \"fcf_debt\": 0.10,\n",
    "        \"interest_coverage\": 1.2,\n",
    "        \"fixed_charge_coverage\": 1.6,\n",
    "        \"dscr\": 1.05,\n",
    "        \"ebitda_margin\": 0.165,\n",
    "        \"ebit_margin\": 0.11,\n",
    "        \"roa\": 0.052,\n",
    "        \"roe\": 0.105,\n",
    "        \"capex_dep\": 1.2,\n",
    "        \"current_ratio\": 1.2,\n",
    "        \"rollover_coverage\": 1.05,\n",
    "    }\n",
    "\n",
    "    fin_t2 = {\n",
    "        \"debt_ebitda\": 3.9,\n",
    "        \"net_debt_ebitda\": 3.4,\n",
    "        \"debt_equity\": 1.7,\n",
    "        \"debt_capital\": 0.60,\n",
    "        \"ffo_debt\": 0.16,\n",
    "        \"fcf_debt\": 0.09,\n",
    "        \"interest_coverage\": 1.5,\n",
    "        \"fixed_charge_coverage\": 1.8,\n",
    "        \"dscr\": 1.10,\n",
    "        \"ebitda_margin\": 0.155,\n",
    "        \"ebit_margin\": 0.10,\n",
    "        \"roa\": 0.050,\n",
    "        \"roe\": 0.10,\n",
    "        \"capex_dep\": 1.1,\n",
    "        \"current_ratio\": 1.1,\n",
    "        \"rollover_coverage\": 1.0,\n",
    "    }\n",
    "\n",
    "    # --- Altman Z components (t0, t1, t2) ---\n",
    "\n",
    "    components_t0 = {\n",
    "        \"working_capital\": 120.0,\n",
    "        \"total_assets\": 1000.0,\n",
    "        \"retained_earnings\": 200.0,\n",
    "        \"ebit\": 80.0,\n",
    "        \"market_value_equity\": 600.0,\n",
    "        \"total_liabilities\": 400.0,\n",
    "        \"sales\": 900.0,\n",
    "    }\n",
    "\n",
    "    components_t1 = {\n",
    "        \"working_capital\": 110.0,\n",
    "        \"total_assets\": 950.0,\n",
    "        \"retained_earnings\": 180.0,\n",
    "        \"ebit\": 75.0,\n",
    "        \"market_value_equity\": 580.0,\n",
    "        \"total_liabilities\": 370.0,\n",
    "        \"sales\": 880.0,\n",
    "    }\n",
    "\n",
    "    components_t2 = {\n",
    "        \"working_capital\": 100.0,\n",
    "        \"total_assets\": 900.0,\n",
    "        \"retained_earnings\": 160.0,\n",
    "        \"ebit\": 70.0,\n",
    "        \"market_value_equity\": 550.0,\n",
    "        \"total_liabilities\": 350.0,\n",
    "        \"sales\": 860.0,\n",
    "    }\n",
    "\n",
    "    # --- Peer data (t0) ---\n",
    "\n",
    "    peers_t0 = {\n",
    "        \"debt_ebitda\": [2.8, 3.0, 3.1],\n",
    "        \"net_debt_ebitda\": [2.5, 2.7, 2.9],\n",
    "        \"debt_equity\": [1.3, 1.4, 1.5],\n",
    "        \"debt_capital\": [0.50, 0.52, 0.54],\n",
    "        \"ffo_debt\": [0.20, 0.22, 0.24],\n",
    "        \"fcf_debt\": [0.14, 0.16, 0.18],\n",
    "        \"interest_coverage\": [2.0, 2.5, 3.0],\n",
    "        \"fixed_charge_coverage\": [1.8, 2.0, 2.2],\n",
    "        \"dscr\": [1.2, 1.3, 1.4],\n",
    "        \"ebitda_margin\": [0.17, 0.18, 0.19],\n",
    "        \"ebit_margin\": [0.115, 0.125, 0.13],\n",
    "        \"roa\": [0.055, 0.06, 0.065],\n",
    "        \"roe\": [0.11, 0.115, 0.12],\n",
    "        \"capex_dep\": [1.1, 1.2, 1.3],\n",
    "        \"current_ratio\": [1.2, 1.3, 1.4],\n",
    "        \"rollover_coverage\": [1.1, 1.2, 1.3],\n",
    "    }\n",
    "\n",
    "    quant_inputs = QuantInputs(\n",
    "        fin_t0=fin_t0,\n",
    "        fin_t1=fin_t1,\n",
    "        fin_t2=fin_t2,\n",
    "        components_t0=components_t0,\n",
    "        components_t1=components_t1,\n",
    "        components_t2=components_t2,\n",
    "        peers_t0=peers_t0,\n",
    "    )\n",
    "\n",
    "    # --- Qualitative factors ---\n",
    "\n",
    "    qual_t0 = {\n",
    "        \"industry_risk\": 3,\n",
    "        \"market_position\": 5,\n",
    "        \"revenue_diversification\": 5,\n",
    "        \"revenue_stability\": 4,\n",
    "        \"business_model_resilience\": 4,\n",
    "        \"management_quality\": 4,\n",
    "        \"governance\": 4,\n",
    "        \"financial_policy\": 3,\n",
    "        \"sovereign_risk\": 3,\n",
    "        \"legal_environment\": 4,\n",
    "        \"transparency\": 4,\n",
    "        \"liquidity_profile\": 3,\n",
    "        \"wc_management_quality\": 4,\n",
    "        \"refinancing_risk\": 3,\n",
    "    }\n",
    "    qual_t1 = qual_t0.copy()\n",
    "\n",
    "    qual_inputs = QualInputs(\n",
    "        factors_t0=qual_t0,\n",
    "        factors_t1=qual_t1,\n",
    "    )\n",
    "\n",
    "    # --- Sovereign inputs ---\n",
    "\n",
    "    sample_sovereign_rating = \"A-\"\n",
    "    sample_sovereign_outlook = \"Negative\"\n",
    "\n",
    "    # --- Run model ---\n",
    "\n",
    "    model = RatingModel(cp_name=\"SampleCorp\")\n",
    "    out = model.compute_final_rating(\n",
    "        quant_inputs,\n",
    "        qual_inputs,\n",
    "        sovereign_rating=sample_sovereign_rating,\n",
    "        sovereign_outlook=sample_sovereign_outlook,\n",
    "        enable_hardstops=False,\n",
    "        enable_sovereign_cap=True,\n",
    "    )\n",
    "\n",
    "    summary = {\n",
    "        \"issuer_name\": out.issuer_name,\n",
    "        \"quantitative_score\": round(out.quantitative_score, 1),\n",
    "        \"qualitative_score\": round(out.qualitative_score, 1),\n",
    "        \"combined_score\": round(out.combined_score, 1),\n",
    "        \"peer_score\": out.peer_score,\n",
    "        \"base_rating\": out.base_rating,\n",
    "        \"distress_notches\": out.distress_notches,\n",
    "        \"hardstop_rating\": out.hardstop_rating,\n",
    "        \"final_rating\": out.final_rating,\n",
    "        \"outlook\": out.outlook,\n",
    "        \"hardstop_triggered\": out.hardstop_triggered,\n",
    "        \"hardstop_details\": out.hardstop_details,\n",
    "        \"sovereign_rating\": out.sovereign_rating,\n",
    "        \"sovereign_outlook\": out.sovereign_outlook,\n",
    "        \"bucket_avgs\": out.bucket_avgs,\n",
    "        \"altman_z_t0\": out.altman_z_t0,\n",
    "        \"flags\": out.flags,\n",
    "        \"rating_explanation\": out.rating_explanation,\n",
    "    }\n",
    "\n",
    "    for k, v in summary.items():\n",
    "        print(f\"{k}: {v}\")\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python (rating_model)",
   "language": "python",
   "name": "rating_model"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.19"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
